export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const REQUEST_SALESMEN = 'REQUEST_SALESMEN';
export const RECEIVE_SALESMEN = 'RECEIVE_SALESMEN';
export const REQUEST_STATUSES = 'REQUEST_STATUSES';
export const RECEIVE_STATUSES = 'RECEIVE_STATUSES';
export const REQUEST_COMPANIES = 'REQUEST_COMPANIES';
export const RECEIVE_COMPANIES = 'RECEIVE_COMPANIES';
export const REQUEST_SALES = 'REQUEST_SALES';
export const RECEIVE_SALES = 'RECEIVE_SALES';
export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';
export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';
export const UPDATE_COMPANY_ITEM = 'UPDATE_COMPANY_ITEM';
export const UPDATE_COMPANY_ITEM_SALES = 'UPDATE_COMPANY_ITEM_SALES';
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const SET_FILTER = 'SET_FILTER';
export const SET_SORTING = 'SET_SORTING';
export const ADD_SALE_REQUEST = 'ADD_SALE_REQUEST';
export const ADD_SALE_SUCCESS = 'ADD_SALE_SUCCESS';
export const ADD_SALE_FAILURE = 'ADD_SALE_FAILURE';
export const DELETE_SALE_REQUEST = 'DELETE_SALE_REQUEST';
export const DELETE_SALE_SUCCESS = 'DELETE_SALE_SUCCESS';
export const DELETE_SALE_FAILURE = 'DELETE_SALE_FAILURE';
export const UPDATE_SALE_REQUEST = 'UPDATE_SALE_REQUEST';
export const UPDATE_SALE_SUCCESS = 'UPDATE_SALE_SUCCESS';
export const UPDATE_SALE_FAILURE = 'UPDATE_SALE_FAILURE';

//Account
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGIN_STEP = 'LOGIN_STEP';
export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

//Admin
export const CREATE_SALESMAN_REQUEST = 'CREATE_SALESMAN_REQUEST';
export const CREATE_SALESMAN_SUCCESS = 'CREATE_SALESMAN_SUCCESS';
export const CREATE_SALESMAN_FAILURE = 'CREATE_SALESMAN_FAILURE';
export const CREATE_STATUS_REQUEST = 'CREATE_STATUS_REQUEST';
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS';
export const CREATE_STATUS_FAILURE = 'CREATE_STATUS_FAILURE';
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export const DELETE_SALESMAN_REQUEST = 'DELETE_SALESMAN_REQUEST';
export const DELETE_SALESMAN_SUCCESS = 'DELETE_SALESMAN_SUCCESS';
export const DELETE_SALESMAN_FAILURE = 'DELETE_SALESMAN_FAILURE';
export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAILURE = 'DELETE_STATUS_FAILURE';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

// Admin - User
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const SET_USER_PASSWORD_REQUEST = 'SET_USER_PASSWORD_REQUEST';
export const SET_USER_PASSWORD_SUCCESS = 'SET_USER_PASSWORD_SUCCESS';
export const SET_USER_PASSWORD_FAILURE = 'SET_USER_PASSWORD_FAILURE';

export const SET_USER_TYPE_REQUEST = 'SET_USER_TYPE_REQUEST';
export const SET_USER_TYPE_SUCCESS = 'SET_USER_TYPE_SUCCESS';
export const SET_USER_TYPE_FAILURE = 'SET_USER_TYPE_FAILURE';
